/**
 * Sample data for template preview
 */
export const SAMPLE_DATA = {
  couple: {
    id: 'sample',
    slug: 'alex-sam',
    groom_name: 'Alex',
    bride_name: 'Sam',
    groom_photo_url: '',
    bride_photo_url: '',
    couple_photo_url: '',
    story: 'We met at a coffee shop in 2020. After 4 years of adventures, we\'re ready to say I do!',
    quote: 'And so the adventure begins...',
    wedding_date: '2026-09-15',
    wedding_time: '10:00',
    ceremony_time: '10:00',
    reception_time: '13:00',
    venue_name: 'The Grand Ballroom',
    venue_address: '123 Love Street, Jakarta',
    maps_url: 'https://maps.google.com',
    maps_embed_url: '',
    dress_code: 'Semi-Formal',
    music_url: '',
    primary_color: '#D4A574',
    secondary_color: '#FFF8F0',
    bg_image_url: '',
    video_url: '',
    video_type: '',
    is_published: true,
    template_id: 1,
    created_at: '2026-08-16',
    updated_at: '2026-08-16',
  },
  countdown: {
    wedding_date: '2026-09-15',
    wedding_time: '10:00',
    ceremony_time: '10:00',
    reception_time: '13:00',
  },
  loveStory: [
    { id: 1, couple_id: 'sample', year: '2020', title: 'First Meet', description: 'We met at a coffee shop', icon: '☕', sort_order: 0 },
    { id: 2, couple_id: 'sample', year: '2021', title: 'First Date', description: 'A romantic dinner by the bay', icon: '🌊', sort_order: 1 },
    { id: 3, couple_id: 'sample', year: '2023', title: 'Moved In', description: 'Our first apartment together', icon: '🏠', sort_order: 2 },
    { id: 4, couple_id: 'sample', year: '2025', title: 'The Proposal', description: 'He said YES!', icon: '💍', sort_order: 3 },
  ],
  schedule: [
    { id: 1, couple_id: 'sample', event_time: '10:00', title: 'Wedding Ceremony', description: 'The main event', sort_order: 0 },
    { id: 2, couple_id: 'sample', event_time: '13:00', title: 'Reception', description: 'Dinner & dancing', sort_order: 1 },
  ],
  gallery: [
    { id: 1, couple_id: 'sample', url: 'https://picsum.photos/400/400?random=1', thumbnail_url: '', caption: 'Us ❤️', sort_order: 0, created_at: '2026-08-16' },
    { id: 2, couple_id: 'sample', url: 'https://picsum.photos/400/400?random=2', thumbnail_url: '', caption: '', sort_order: 1, created_at: '2026-08-16' },
    { id: 3, couple_id: 'sample', url: 'https://picsum.photos/400/400?random=3', thumbnail_url: '', caption: '', sort_order: 2, created_at: '2026-08-16' },
    { id: 4, couple_id: 'sample', url: 'https://picsum.photos/400/400?random=4', thumbnail_url: '', caption: '', sort_order: 3, created_at: '2026-08-16' },
    { id: 5, couple_id: 'sample', url: 'https://picsum.photos/400/400?random=5', thumbnail_url: '', caption: '', sort_order: 4, created_at: '2026-08-16' },
    { id: 6, couple_id: 'sample', url: 'https://picsum.photos/400/400?random=6', thumbnail_url: '', caption: '', sort_order: 5, created_at: '2026-08-16' },
  ],
  wishes: [
    { id: 1, couple_id: 'sample', guest_name: 'Best Friend', message: 'Congratulations! So happy for you both! 🎉', is_approved: true, created_at: '2026-08-16' },
    { id: 2, couple_id: 'sample', guest_name: 'Mom', message: 'My babies, forever happiness!', is_approved: true, created_at: '2026-08-16' },
  ],
  gifts: [],
  music: { id: 1, couple_id: 'sample', title: 'Perfect', url: '', is_active: true, sort_order: 0, created_at: '2026-08-16' },
};
